---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kjdte/public_html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp -R css/ $DEPLOYPATH
    - /bin/cp -R html/ $DEPLOYPATH
    - /bin/cp -R img/ $DEPLOYPATH